# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CountryGeography' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CountryGeography

  target 'CountryGeographyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CountryGeographyUITests' do
    # Pods for testing
  end

end
